[package]
name = "scigui"
version = "0.1.0"
edition = "2021"

[dependencies]
argmin = "0.10.0"
eframe = "0.27.2"
egui = "0.27.2"
egui_plot = "0.27.2"
image = "0.25.1"
rfd = "0.14.1"
sci-rs = "0.3.13"
